# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:02:27+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import RootModel


class JsonGetResponse(RootModel[Optional[Dict[str, Any]]]):
    root: Optional[Dict[str, Any]] = None
